### ISSUE TITLE
labels on waveform fits plot for cases of DC or deviatoric constraints

### ISSUE THREAD

**Issue by carltape** [uafgeotools/mtuq#178] opened 2022-06-09 21:46 UTC
It would be nice to have some indication in the waveform fits plot of any constraint that was used. Consider the case where any parameter (Mw, strike, dip, rake, gamma, delta) is fixed. Then a label could be added such as 
delta 0*
or
delta (0)
If that were the only constrained parameter, then it would be a deviatoric inversion. Or
gamma 0* delta 0*
or
gamma (0) delta (0)
would indicate a double couple inversion.
Or Mw (6.21) or Mw 6.21* would indicated a fixed-magnitude constraint. And so on. This would allow us to distinguish between cases where parameters were constrained and where they were unconstrained. At present, the label
gamma 0 delta 0
could either be a DC-constrained inversion or a FMT inversion that happened to find a double couple as the best-fitting moment tensor.

**Comment by rmodrak** [comment] 2022-06-09 21:55
An asterisk for a fixed parameter sounds like a nice convention.  Unfortunately, there's not an easy fix using the existing plotting function arguments.  An optional keyword argument might be a possibility.

**Comment by rmodrak** [comment] 2023-08-26 22:51
Duplicate of #221

**Closed by rmodrak** 2023-08-26 22:51 UTC
